<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>1.0.0</Version>
    <InformationalVersion Condition="'$(MSBuildProjectName)' == 'NPEduTools.App' Or '$(MSBuildProjectName)' == 'NPEduTools.Host'">v1.0.0 · EVA-01（初号机）</InformationalVersion>
    <NuGetLockFilePath Condition="'$(PackageLockDirectory)' != ''">$(PackageLockDirectory)/$(MSBuildProjectName).lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>
