<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NPEduTools.Contracts/NPEduTools.Contracts.csproj" />
    <ProjectReference Include="../NPEduTools.Host/NPEduTools.Host.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Target Name="CopyHostBundle" AfterTargets="Build">
    <ItemGroup>
      <HostBundle Include="../NPEduTools.Host/bin/$(Configuration)/net10.0/**/*" />
    </ItemGroup>
    <Copy SourceFiles="@(HostBundle)" DestinationFiles="@(HostBundle->'$(OutDir)Host/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
