$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent
$assetRoot = Join-Path $projectRoot 'images/branding'
$destination = Join-Path $projectRoot 'src/NPEduTools.App/Resources/Branding.xaml'
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('<!-- Generated by scripts/sync-branding.ps1 from the approved SVG assets. Do not edit paths here. -->')
$lines.Add('<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
foreach ($variant in @(@('BrandLogo','npedutools-logo.svg'), @('BrandLogoSmall','npedutools-logo-small.svg'), @('BrandLogoLight','npedutools-logo-mono-light.svg'))) {
    $document = [xml]::new(); $document.XmlResolver = $null
    $document.Load((Join-Path $assetRoot $variant[1]))
    $svg = $document.DocumentElement
    if ($svg.viewBox -ne '169.5 153.5 920 920' -or $svg.SelectNodes('*[local-name()!="path" and local-name()!="title" and local-name()!="desc"]').Count -ne 0) {
        throw "Unsupported SVG structure: $($variant[1]). Review the conversion before updating resources."
    }
    $lines.Add("  <DrawingImage x:Key=`"$($variant[0])`">")
    $lines.Add('    <DrawingImage.Drawing><DrawingGroup>')
    # Preserve the SVG viewport and transparent padding, rather than cropping to visible path bounds.
    $lines.Add('      <GeometryDrawing Brush="Transparent"><GeometryDrawing.Geometry><RectangleGeometry Rect="169.5,153.5,920,920" /></GeometryDrawing.Geometry></GeometryDrawing>')
    foreach ($path in $svg.SelectNodes('*[local-name()="path"]')) {
        if ($path.fill -notmatch '^#[0-9A-Fa-f]{6}$' -or $path.HasAttribute('transform') -or $path.HasAttribute('style') -or $path.HasAttribute('stroke')) {
            throw "Unsupported SVG path: $($variant[1])"
        }
        $geometry = [Security.SecurityElement]::Escape($path.d)
        $lines.Add("      <GeometryDrawing Brush=`"$($path.fill)`" Geometry=`"F1 $geometry`" />")
    }
    $lines.Add('    </DrawingGroup></DrawingImage.Drawing>')
    $lines.Add('  </DrawingImage>')
}
$lines.Add('</ResourceDictionary>')
New-Item -ItemType Directory -Path (Split-Path $destination) -Force | Out-Null
[IO.File]::WriteAllLines($destination, $lines, [Text.UTF8Encoding]::new($false))
Write-Output "Updated WPF vectors: $destination"
